# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostcomment',
            name='date_added',
            field=models.DateField(),
        ),
    ]
