# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_auto_20151203_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostcomment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
