# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0007_auto_20151205_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=b'http://pethealthsupplements.com.au/wp-content/uploads/2015/06/         tumblr_static_mom-dog-with-puppies.jpg', upload_to=b'Desktop/Python/awp-project/pic-folder'),
        ),
    ]
