# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0008_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=b'avatars/dog_with_puppies.jpg', upload_to=b'avatars/'),
        ),
    ]
